### ISSUE TITLE
Use as a node\browserify npm module

### ISSUE THREAD

**Issue by gothy** [zendesk/cross-storage#10]
There's an option to install as an npm-module, but did anyone actually tried to use it from as a node-module from browserify? It's not possible since it's not exporting anything from the root index.js

**Comment by danielstjules** [comment]
This should work:
``` javascript
var client = require('cross-storage/lib/client.js');
var hub    = require('cross-storage/lib/hub.js');
```

I'll addan index.js to lib and export the two though.

**Comment by gothy** [comment]
var client = require('cross-storage/lib/client.js');
gives you an empty Object as a result since client.js is not exporting anything via module.exports.

You can check out this article to prepare the library code for any kind of usage with global, AMD and CommonJS styles http://oli.me.uk/2013/07/21/exporting-through-amd-commonjs-and-the-global-object/

**Comment by danielstjules** [comment]
hah, oops. I'm familiar with AMD in a browser environment (https://github.com/danielstjules/blankshield/blob/master/blankshield.js#L150-L168 https://github.com/danielstjules/hoops/blob/master/lib/hoops.js#L191-L213), just woke up and figured I'd already done the work. :)

I'll have a fix for this throughout the week.

**Comment by gothy** [comment]
Great, thanks! :)

**Comment by danielstjules** [comment]
So sorry for the late reply on this: https://github.com/zendesk/cross-storage/commit/81ad623f89940520a3bf6e593fe8079e52c5e6e5

**Comment by danielstjules** [comment]
Closing, please see https://github.com/zendesk/cross-storage/releases/tag/0.7.0 :)
