### ISSUE TITLE
SCRIPT5: Access is Denied in IE10

### ISSUE THREAD

**Issue by sureleo** [zendesk/cross-storage#13]
Hi,

I'm getting a very weird error in IE10, which is "SCRIPT5: Access is Denied". I hosted my the example in this repository on GoogleDrive. I need both IE10 and HTTPS.

[Client1](https://a88addf0d39c124f02458bc579b419d5ac411912-www.googledrive.com/host/0ByJbkm97onNkfnZUWHpaTEtLeTZVRGZ6VHZoc3FPS2tJcXVMOWZULUlOQTE2X1lSX1hRZlk/client1.html)
[Client2](https://6cd83a1745cf7bb25ac2aaaa971c235f0aeb937e-www.googledrive.com/host/0ByJbkm97onNkfmFlc2NJOUJOMnhpVlRfYThqWjlUdWI0QndJcmRNWVdQR282RGs4Y0huek0/client2.html)
[Hub](https://7040c964de9eb6a266e2ef3dac79b11ec155d009-www.googledrive.com/host/0ByJbkm97onNkfnI0a2loNnpxMWRLX0dOVW9CcllvU1J4cFFKZWVDa1QzdTFub0pTakNRUW8/hub.html)

I will get that error when I first open the client, but it works fine if I refresh the page. It also works perfectly on my friend's laptop (without refreshing), but we have the same IE security level settings.

Thanks in advance.

Leo

**Comment by danielstjules** [comment]
Are all security zones at their defaults? Is "Protection Mode" enabled?

**Comment by danielstjules** [comment]
I'm running IE10 in a dev VM and it works so far

![screen shot 2015-06-08 at 7 37 13 pm](https://cloud.githubusercontent.com/assets/817212/8049595/07641506-0e16-11e5-9018-3a5d453f1bb0.png)

Here's my security/privacy settings (which I believe are default - haven't changed them)

![screen shot 2015-06-08 at 7 37 42 pm](https://cloud.githubusercontent.com/assets/817212/8049598/14344904-0e16-11e5-8c59-d2c25b9c90a2.png)

![screen shot 2015-06-08 at 7 38 01 pm](https://cloud.githubusercontent.com/assets/817212/8049599/161cd876-0e16-11e5-8be8-db6145503c7f.png)

**Comment by sureleo** [comment]
Hi Daniel,

Thanks for your kindly help. I swear I didn't change anything but everything worked after I came to office! I'm thinking the only reason could be the Google Drive web hosting is not stable.

Please close this issue I will let you know if the same thing happens again.

Cheers :-)

**Comment by danielstjules** [comment]
Glad to hear it! :)
