### ISSUE TITLE
nexus 4, android 5.1 , Chrome 43

### ISSUE THREAD

**Issue by Daniel1984** [zendesk/cross-storage#16]
Error: CrossStorageClient could not connect at eval (.../node_modules/cross-storage/lib/client.js:151:14)

Only happens on my nexus 4. Is there a known issue or maybe I'm just missing something?

**Comment by danielstjules** [comment]
I've got the same setup :) Is it maybe a latency issue, if using data. Have you tried increasing the timeout?

**Comment by Daniel1984** [comment]
Hey, thanks, I increased it to 5s and it works :+1:
