### ISSUE TITLE
Error when message.data is not string

### ISSUE THREAD

**Issue by ericfong** [zendesk/cross-storage#17]
Hi

Thanks for your works.

I just got 
```
Uncaught TypeError: message.data.indexOf is not a function
```
in https://github.com/zendesk/cross-storage/blob/master/lib/client.js#L288

while putting cross-storage with webpack, browser-sync and react-hot-reload.
Some of my module also use window messaging system which have message.data in Number type.

Please use typeof to check the message.data?

**Comment by danielstjules** [comment]
Thanks for letting us know! We'll get a fix out soon.

**Comment by danielstjules** [comment]
Fixed in https://github.com/zendesk/cross-storage/commit/210c8462c5032af24b600f25293ae6cada80fb00 Thanks!
