### ISSUE TITLE
Storage update event

### ISSUE THREAD

**Issue by TNAJanssen** [zendesk/cross-storage#19]
Send an update message an let the application create a trigger (so when another tab changes it the other can detect this)

    window.addEventListener('storage', function(e) {
      window.parent.postMessage('cross-storage:updated', '*');
    });

**Comment by danielstjules** [comment]
Interesting idea. Rather than just updated, I wonder if it'd be worth emitting events for any cross-storage client request, if desired.

**Comment by danielstjules** [comment]
Issue's pretty old - closing for now. If there's any interest, a PR is welcome!

**Comment by alexilyaev** [comment]
@danielbreves I'm using CrossStorage to implement a Single-Sign-On, where the user can login in one app domain and won't have to login in another app domain.

I would like to cache a value from CrossStorage into localStorage and then remove it when it is removed from CrossStorage (this would help a lot in terms of performance).

Having a hook on CrossStorage events would be awesome.
I'm willing to PR if you can outline the needed steps to achieve this.

Expected API:
```js
const crossStorage = new CrossStorageClient(...);

crossStorage.on('set', (key, value) => { ... });
crossStorage.on('del', (key) => { ... });
```

**Comment by danielbreves** [comment]
@alexilyaev did you mean to mention @danielstjules?

**Comment by alexilyaev** [comment]
@danielbreves Yep, sorry, updated :-)
