### ISSUE TITLE
Option or methods to skip serialization

### ISSUE THREAD

**Issue by eads** [zendesk/cross-storage#21]
We're trying to use this over at NPR as a drop-in solution to access and set localstorage variables used for analytics from the sub-domains we use for special projects. I love the overall design of the library and the high quality of the code, especially the use of ES6 promises.

However, it doesn't work as a drop-in solution because of the choice to serialize the data in and out of localstorage. Because my team and our projects don't have control over how those variables are set on our parent website and nobody thought to adopt cross-storage when they originally decided to use LocalStorage to stash this information, we can't use the library without modification. 

For now, we're going to maintain a fork which skips the json serialization and directly sets/gets the values out of LocalStorage on the hub. But I'm curious if you'd be open to a initialization option that skips the serialization or alternate get/set methods (`getDirect`?) that accomplish the same. Since we're forking anyway, we could easily make such a thing and submit a pull request.

I suspect this would help spur adoption, because we can't be the only ones who need to retrofit a cross domain storage solution into an existing ecosystem of sites where the choice of storage format is out of their control.

**Comment by danielstjules** [comment]
Sorry for the late reply! I think a `getRaw` function could be useful, as you mentioned :)

**Comment by eads** [comment]
Oh, no worries whatsoever! We've been buried by election coverage as it is and are only now emerging to be able to contribute back to open source projects we've been using. 

Me or someone on my team will tackle this in the next month or so! We'd be very appreciative if this landed in the official version so that we don't have to maintain our own. 

Tangentially, this thing has been a godsend and the architecture gives me some ideas for the next generation of our responsive iframe library.

**Comment by danielstjules** [comment]
I've gone over https://github.com/zendesk/cross-storage/pull/26 and the proposed solution is definitely in line with the discussion here, much appreciated!

But I've been thinking about this more, and cross-storage is probably doing too much. I think it would make sense to simply drop TTLs and stop serializing altogether. It would be much more flexible, though it would be a major breaking change with no clear upgrade path. For users looking to upgrade, you could perhaps ship some code in the hub that looked through all stored items and deserialized them if they followed the format `{value, expire}`

**Comment by eads** [comment]
Awesome, we appreciate it. IMHO, cross-storage is a little too opinionated about the storage format, which probably acts as a barrier to adoption. Raw values are easy enough to serialize however the developer using cross-storage sees fit. 

The upgrade path is difficult, which is why we proposed an alternate mode. But that doesn't help migrate anyone to use the raw values.

**Comment by danielstjules** [comment]
> MHO, cross-storage is a little too opinionated about the storage format, which probably acts as a barrier to adoption.

Agreed! Scope changed. I had actually intended to build it out as a more complex store, but that didn't happen. Some functionality (TTLs) are remnants of that early design. Operating just on raw values should be much simpler and v1.0.0 provides exactly that :)

I think the project has been successfully cut down to its most essential parts.

**Comment by danielstjules** [comment]
Here's a possible migration solution for those looking to use 1.0.0 and not losing existing data. (Haven't tested)

``` javascript
<script>
/**
 * Migration function to update keys set by cross-storage ~8 and below to be
 * to be compatible with cross-storage 1.0. Assumes no JSON objects were
 * previously stored with a key named "value"
 */
function migrate() {
  var i, key, item, value;
  for (i = 0; i < localStorage.length; i++) {
    try {
      key = localStorage.key(i);
      item = JSON.parse(localStorage.getItem(key));

      if ('value' in item) {
        localStorage.setItem(key, item.value);
      }
    } catch (e) {
      // no-op
    }
  }

  migrate();
</script>
```
