### ISSUE TITLE
This library look great but don't know how to use this library in angular2.0 (final) project?

### ISSUE THREAD

**Issue by PoppyPham** [zendesk/cross-storage#30]

**Comment by danielstjules** [comment]
Here's some examples that might help!
* https://www.thepolyglotdeveloper.com/2016/01/include-external-javascript-libraries-in-an-angular-2-typescript-project/
* https://medium.com/@s_eschweiler/using-external-libraries-with-angular-2-87e06db8e5d1#.lcrny4o3c
* https://coryrylan.com/blog/angular-2-cli-adding-third-party-libraries

Then it's just a matter of configuring the clients to point to your hub! :)

**Comment by PoppyPham** [comment]
Thank a lot @danielstjules
