### ISSUE TITLE
Multiple iFrames on same page to the same Hub

### ISSUE THREAD

**Issue by JasonLi914** [zendesk/cross-storage#34]
Hi, I am running into behavior with CrossStorage where if you try to initialize multiple CrossStorageClients from the same webpage that connect to the same Hub, it creates multiple unique iframes on the page. I was wondering if this behavior was desired, or if it would be possible to make it so that if the current webpage already has an iframe connecting it to the target Hub, any future instances of CrossStorageClient on the same page will use the existing iframe instead of creating their own. 

This problem arises because a particular component I am currently developing creates a CrossStorageClient per instance, but the same webpage may already have an iframe linked to that hub.

I would also be willing to write this PR. Please let me know your thoughts, thank you for your time!

**Comment by JasonLi914** [comment]
Actually, will close this issue now, have decided to just search for the frame id on the page and use the same one.

**Comment by danielstjules** [comment]
While that works, my suggestion would be to have a global instance shared among all components.
