### ISSUE TITLE
Support for Different Storage via Adapter

### ISSUE THREAD

**Issue by JasonLi914** [zendesk/cross-storage#35]
Hi, I was wondering if it would be possible for CrossStorageHub to be able to support being initialized with  different types of storage (i.e. indexedDb, WebSQL), rather than solely using localStorage. The reason for this is that localStorage may not be desired by users because of it's limited storage capacity. My thoughts were that this would be implemented via an Adapter and localStorage will be the default storage option when a different one isn't specified, so that this change will not be breaking for existing users of cross-storage. Would be willing to write this PR as well. Please let me know your thoughts, thanks!

**Comment by danielstjules** [comment]
I see you've started working on it in https://github.com/JasonLi914/cross-storage/commit/d83b474bb10bef9c7f064d8fc62f2bdc1c688d65 The LocalStorageAdapter is looking good :)

It's def an interesting idea, but I should probably remind that this library essentially [isn't compatible with Safari](https://github.com/zendesk/cross-storage#compatibility). If one's writing a bunch of application logic that's dependent on cross-domain indexedDb, what about Safari users? My thinking was that if it's just localStorage, you probably aren't storing anything too complicated, and can hopefully fallback to a server or cookie as needed for safari. But for something as heavy/involved as indexedDb, what then? I'd almost want to dissuade devs from using anything other than the "LocalStorageAdapter"
