### ISSUE TITLE
zendesk.cross-storage.s3bucket.missing.png

### ISSUE THREAD

**Issue by eddo888** [zendesk/cross-storage#39]
https://s3.amazonaws.com/es6-promises/

```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>es6-promises</BucketName>
<RequestId>48931BFEC0D168DE</RequestId>
<HostId>
rc0/qQw4NzN1j5r3tv5dY50xRFPyODLC8OCRV07AHUDA8xtQ9DlQGMXOICaUOvRnwISDpxTN0p0=
</HostId>
</Error>
```
![zendesk cross-storage s3bucket missing](https://cloud.githubusercontent.com/assets/2610223/26427657/171b2d46-4121-11e7-9bd3-c18a499aba65.png)

**Comment by danielstjules** [comment]
Oops, looks like they moved it! You can download the minified file from https://github.com/stefanpenner/es6-promise
