### ISSUE TITLE
"get" method doesn't return data

### ISSUE THREAD

**Issue by dchirutac** [zendesk/cross-storage#44]
Hi, thanks for the great library.

I've been set my 
**Hub**:
 
         CrossStorageHub.init([
          { origin: /.*account.mydomain$/, allow: ['get', 'set', 'del', 'getKeys'] },
          { origin: /.*site1.mydomain$/, allow: ['get'] },
          { origin: /.*site2.mydomain$/, allow: ['get'] }

        ]);
**Client** for account.mydomain

      var storage = new CrossStorageClient('http://account.mydomain/hub.html');

**When** I set the key 
      
     storage.onConnect()
            .then(function () {
                storage.set('userData', JSON.stringify(value));
            }).then(function (res) {
                console.log(res);
            }).catch(function (err) {
                console.log(err);
            });

It **works** perfectly, **but** when I'm trying to get this key value the result is always `undefined`

     storage.onConnect()
            .then(function () {
                storage.get('userData');
            }).then(function (res) {
                console.log(res);
            }).catch(function (err) {
                console.log(err);
            });

What am I doing wrong?
Thank you for any help!

**Comment by danielstjules** [comment]
Try
```javascript
storage.onConnect()
  .then(function () {
      return storage.get('userData');
  }).then(function (res) {
      console.log(res);
  }).catch(function (err) {
      console.log(err);
  });
```

**Comment by dchirutac** [comment]
You are right!!!. Thanks
