### ISSUE TITLE
getOrigin returns :// in IE9

### ISSUE THREAD

**Issue by bolshchikov** [zendesk/cross-storage#6]
`_getOrigin` method of CrossStorageClient return `://` in IE9 in the following line`origin = uri.protocol + '//' + uri.host;` because `uri.protocol` is `:` and `uri.host` empty string.
Why not to use origin and host of `window.location` if it's available, and as a fallback, use current implementation?

**Comment by nikaspran** [comment]
@danielstjules The issue still exists in IE11 when using protocol-relative urls:

IE11
```
>> CrossStorageClient._getOrigin('//example/hub.html')
  "://example"
```

Chrome
```
>> CrossStorageClient._getOrigin('//example/hub.html')
  "http://example"
```

This is because [`uri.protocol`](https://github.com/zendesk/cross-storage/blob/master/lib/client.js#L102) returns `:` for protocol-relative urls in IE.

**Comment by danielstjules** [comment]
I don't currently have access to IE11, but I'm able to reproduce with IE10.

``` javascript
var getOrigin = function(url) {
  var uri, origin;

  uri = document.createElement('a');
  uri.href = url;

  if (!uri.host) {
    uri = window.location;
  }

  origin = uri.protocol + '//' + uri.host;
  origin = origin.replace(/:80$|:443$/, '');

  return origin;
};

getOrigin('//example/hub.html')
// => "://example"
getOrigin('//www.example/hub.html')
// => "://www.example"
getOrigin('http://www.example/hub.html')
// => "http://www.example"
```

It's getting late, so I won't be looking into this tonight. In the meantime, could you avoid the combo of protocol + path relative urls?

**Comment by nikaspran** [comment]
Any progress on this? I'd try my hand at a pull request but I'm not sure about the best way to fix this. I guess if the protocol is missing we could take it from the window.location instead. What do you think?

**Comment by danielstjules** [comment]
Sorry for taking so long with this. I'll have a fix rolled out in the next 20 minutes.

**Comment by danielstjules** [comment]
@nikaspran Updated, check out 0.6.1 :) Thanks, and sorry again for the delay.

**Comment by nikaspran** [comment]
@danielstjules thank you so much - amazing response time!
